name: PHP Composer

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"

    name: PHP ${{ matrix.php-versions }} test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use PHP ${{ matrix.php }}
      run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run tests
      run: composer test
